V2 updated Stylesheet Helpers
umbraco/Umbraco.Playwright.Testhelpers pull request #38
Opened 2023-11-20 04:38 UTC by nhudinh0309

Added StylesheetUiHelper 
Imported StylesheetUiHelper into UiHelper and added goToBackOffice and waitForTimeout to avoid using page in tests
Updated StylesheetApiHelper
Bumped version

2023-11-21 10:00 UTC, andr317c requested changes

2023-11-22 04:00 UTC, nhudinh0309 commented on lib/helpers/UiHelpers.ts
> +import { StylesheetUiHelper } from "./StylesheetUiHelper";
we need to import StylesheetUiHelper here in case we want to use its methods in tests.

2023-11-22 07:16 UTC, andr317c commented on lib/helpers/UiHelpers.ts
> +import { StylesheetUiHelper } from "./StylesheetUiHelper";
I see, that makes a lot of sense!

2023-11-22 08:38 UTC, andr317c requested changes

2023-11-22 08:38 UTC, andr317c commented on lib/helpers/StylesheetUiHelper.ts
> +        await this.ruleNameTxt.clear();
```suggestion
```

2023-11-22 08:38 UTC, andr317c commented on lib/helpers/StylesheetUiHelper.ts
> +        await this.ruleNameTxt.clear();
```suggestion
```

2023-11-22 08:38 UTC, andr317c commented on lib/helpers/StylesheetUiHelper.ts
> +        await this.ruleSelectorTxt.clear();
```suggestion
```

2023-11-22 08:57 UTC, andr317c approved these changes
Looks good!

2023-11-22 08:57 UTC, merged